/**
 * Sitemap `lastmod` values, read from content frontmatter.
 *
 * The sitemap is generated by @astrojs/sitemap in astro.config.ts, which runs
 * outside the Astro runtime and so cannot read content collections. This module
 * reads the same MDX files directly and maps each entry's `updatedDate` to its
 * registry path, so `lastmod` always reports a real, authored update date.
 *
 * Pages with no authored date (home, about, contact, the legal pages) get no
 * `lastmod` at all — an omitted value is correct, a guessed one is not.
 *
 * Only the content directories are read; inclusion, exclusion, and canonical
 * URLs are unchanged and stay owned by astro.config.ts and the page registry.
 */
import { readdirSync, readFileSync } from "node:fs";

import { PAGES, type SitePage } from "../config/pages";

/** Content collections, relative to this file. Must match content.config.ts. */
const CONTENT_DIRS = ["../content/pillars/", "../content/articles/", "../content/tools/"] as const;

const FRONTMATTER = /^---\r?\n([\s\S]*?)\r?\n---/;

/** `YYYY-MM-DD`, optionally with a time, as the content schema accepts. */
const DATE_VALUE = /^\d{4}-\d{2}-\d{2}(?:[T ][\d:.+Z-]+)?$/;

/**
 * Value of a top-level frontmatter key. Indented lines (e.g. `faq` items) never
 * match, so a nested `question:` cannot be mistaken for a page field.
 */
function field(frontmatter: string, name: string): string | undefined {
  const match = new RegExp(`^${name}:[ \\t]*(.*)$`, "m").exec(frontmatter);
  return match?.[1]?.trim().replace(/^["']|["']$/gu, "");
}

/** ISO timestamp of a frontmatter date, or undefined if it is missing or unusable. */
function isoDate(value: string | undefined): string | undefined {
  if (!value || !DATE_VALUE.test(value)) return undefined;
  const parsed = new Date(value);
  return Number.isNaN(parsed.getTime()) ? undefined : parsed.toISOString();
}

/**
 * Registry path → last update timestamp, for every published content entry.
 * Draft entries are skipped: they are not built, so they are never in a sitemap.
 */
export function contentLastmodByPath(): Map<string, string> {
  const pathById = new Map((PAGES as readonly SitePage[]).map((page) => [page.id, page.path]));
  const lastmod = new Map<string, string>();

  for (const dir of CONTENT_DIRS) {
    const base = new URL(dir, import.meta.url);

    for (const file of readdirSync(base)) {
      if (!file.endsWith(".mdx")) continue;

      const frontmatter = FRONTMATTER.exec(readFileSync(new URL(file, base), "utf8"))?.[1];
      if (!frontmatter) continue;
      if (field(frontmatter, "draft") === "true") continue;

      const path = pathById.get(field(frontmatter, "pageId") ?? "");
      const updated = isoDate(field(frontmatter, "updatedDate"));
      if (path && updated) lastmod.set(path, updated);
    }
  }

  return lastmod;
}
